spring:
  application:
    name: IDENTITY-SERVICE
  config:
    import: optional:configserver:http://localhost:8888




#eureka:
#  client:
#    service-url:
#      defaultZone : http://u:p@localhost:8761/eureka/