server:
  port: 9898
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schooldb?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: '{cipher}cc48ffdba008108072cb09322ead2846f7cac48df18996778418e24d6ec75caf'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  