spring:
  application:
    name: SWIGGY-APP
  config:
    import: optional:configserver:http://localhost:8888


#eureka:
#  client:
#    service-url:
#      defaultZone : http://u:p@localhost:8761/eureka/

---
spring.config.activate.on-profile: docker
# When referencing the config server from another container,
# use the service name (as defined in your Docker Compose file) instead of localhost
spring.cloud.config.uri: http://config-server:8888